baseURL: https://thirat-wongwaisayawan-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Thirat (Pon) Wongwaisayawan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: My website Portfolio
    title: Hi, I'm Thirat
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 
        title: 3 Canalside Walk
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: thiratw.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7391268886
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
       # url: https://www.twitter.com
#- icon: fa-facebook
 #       label: Facebook
  #      url: https://www.facebook.com
      #- icon: fa-instagram
       # label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Ponthirat
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/thirat/
  image: lbs.jpg
  name: Thirat Wongwaisayawan
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: About Me
        title: About Me
        url: blogs/about
      - image: Brexit.jpg
        subtitle: Analysis of Brexit Election
        title: Brexit Analysis
        url: blogs/Brexit
      - image: avengers.jpg
        subtitle: Analysis of IMDB dataset
        title: IMDB dataset
        url: blogs/IMDB
      - image: elections.jpg
        subtitle: Analysis of past US elections
        title: Elections in the US
        url: blogs/US
      - image: finance.jpg
        subtitle: We analysed stocks in the NYSE market
        title: Financial Stock Analysis
        url: blogs/Financial
      - image: pic06.jpg
        subtitle: Wait and See
        title: Project
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "This is Thirat's R portfolio!"
    title: Why?
    url: blogs
